# Generated by Django 4.0.2 on 2022-02-28 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('age', models.IntegerField(default=18, null=True)),
                ('social_security', models.CharField(max_length=9, null=True)),
                ('job_title', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=256, null=True)),
                ('current_price', models.CharField(max_length=256, null=True)),
                ('rent_amount', models.CharField(max_length=256, null=True)),
                ('tentants', models.ManyToManyField(to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=256, null=True)),
                ('employer_address', models.CharField(max_length=256, null=True)),
                ('workers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(null=True)),
                ('bank_name', models.CharField(max_length=256, null=True)),
                ('bank_address', models.CharField(max_length=256, null=True)),
                ('bank_routing', models.BigIntegerField(null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
