# Generated by Django 4.0.2 on 2022-02-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_routing',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
