# Generated by Django 4.0.2 on 2022-02-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='workers',
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employer'),
        ),
    ]
